sudo: false
language: rust
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
rust:
- stable
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- "travis-cargo build &&\ntravis-cargo doc"
after_success:
- travis-cargo doc-upload
- travis-cargo coveralls --no-sudo --verify
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - secure: HnfO26DIDzo7ROvcC4PMeWbfkrgtI+WipliEzNPUaelWpCNp0PLGjaUe22Q0iBLXvHcxuc8v3yOI+LFQkiWpajaVCITEYZd8AJ6zfEfsxiSI3AM/kGetC12zNLl9iVwEU1eEX50ZwTFcUz38p1mFsukWh4ItZ5BGxUz6DALa19M7YxsoHWsp7TQf+DHTVzTIphqDMB75MPDBdybh94T6ENI6uxGk0Aj90HcknNrsyrvBCE32ELPjYZEWMPomjOh6hH6g5mnmNQtI6pac2R623ouZ46NWuNGLsUpvLIe+r4AWVWtIr2z10IU4Nn2xxvY7NdQRRE7320XlQcfUgXKWjA3ZtPUBI1p89KM4kyrQKcuEZHiBK4mvEgNIUx2aI1Z3ijUkamhz8hP6a1glmVxSsWvfQTAqG7ntpnCw2764haxtF2UmKLmXKfVxOf9JYntMVQ1AZQTEwc4Ghfi1hmN6NhWk5KT0HA5T4rhYWSUjgRT2JvzqB8AjDNBLLaqKa/0GfE48efdeel1bo1lsENCJyIRv16VYzkuGnK2qiOJZJiV9qV+fXEF2ccMlXuX6mqqEgnS2GrUZQGPU5kEAbqbHeMYNKMNf5v9zKALenFkOASLtYC23rRgfvPd+aoKhspcVEzBz1wpkF5DQoU1ZPdxdXiAP1K6uwjJjnUxRNxSpOMw=
